# Site settings
title: kosop 
description: >
    이것 저것 하고 있습니다. 사진•영상•영화•음악•비평 등
author: 고윤지
email: 12149km@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kosop7.github.io" # the base hostname & protocol for your site

disqus_shortname: kosop-blog

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
